# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - aubo_arm_controller  # <== 必须与 Gazebo 加载的控制器真名保持绝对一致

  aubo_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory  # <== 补上了频道名，消除现在的报错
    default: true
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
      - gripper1_joint
      - gripper2_joint