controller_manager:
  ros__parameters:
    update_rate: 100 # 控制频率 100Hz
    use_sim_time: true

    # 1. 关节状态广播器（读取虚拟编码器数据）
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 2. 机械臂轨迹控制器（接收 MoveIt 或代码下发的轨迹点）
    aubo_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

aubo_arm_controller:
  ros__parameters:
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
      - gripper1_joint
      - gripper2_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
