#!/usr/bin/env python3
"""Generate a rebar pick-and-place station USD layer for Isaac Sim.

The station sits inside the arm's reach in front of the robot (the arm mount
is rotated 180 degrees about Z, so the arm workspace opens toward -X in the
robot frame). It provides a low table, two support blocks that keep the bar
from rolling, and one dynamic rebar cylinder modelled after the nominal
specimen used by the object_detection pipeline (24 mm diameter, 1 m length).
"""

from __future__ import annotations

import argparse
from pathlib import Path

REBAR_DENSITY_KG_M3 = 7850.0


def _vec(values):
    return ", ".join(f"{value:g}" for value in values)


def _cube(name, position, size, color, indent=8, material=None):
    pad = " " * indent
    schemas = ["PhysicsCollisionAPI"]
    body = []
    if material is not None:
        schemas.append("MaterialBindingAPI")
        body.append(
            f"{pad}    rel material:binding:physics = </World/RebarStation/{material}>"
        )
    schema_text = (
        " (\n{}    prepend apiSchemas = [{}]\n{})".format(
            pad, ", ".join(f'"{s}"' for s in schemas), pad
        )
        if schemas
        else ""
    )
    lines = [
        f'{pad}def Cube "{name}"{schema_text}',
        f"{pad}{{",
        f"{pad}    double size = 1",
        f"{pad}    color3f[] primvars:displayColor = [({_vec(color)})]",
        f"{pad}    bool physics:collisionEnabled = 1",
    ]
    lines.extend(body)
    lines.extend(
        [
            f"{pad}    double3 xformOp:translate = ({_vec(position)})",
            f"{pad}    double3 xformOp:scale = ({_vec(size)})",
            (
                f"{pad}    uniform token[] xformOpOrder = "
                '["xformOp:translate", "xformOp:scale"]'
            ),
            f"{pad}}}",
        ]
    )
    return "\n".join(lines)


def generate(
    station_x,
    station_y,
    radius,
    length,
    table_height,
):
    # Steel bar mass from the cylinder volume; keeps grip-force math honest.
    mass = REBAR_DENSITY_KG_M3 * 3.141592653589793 * radius**2 * length

    # Keep the supports well inside the ends for every configured bar length.
    block_size = (0.1, 0.12, 0.06)
    block_offset_x = length * 0.3
    block_top_z = table_height + block_size[2]
    rebar_z = block_top_z + radius

    rust = (0.45, 0.3, 0.2)
    steel_blue = (0.18, 0.24, 0.32)
    block_yellow = (0.85, 0.65, 0.1)

    lines = [
        "#usda 1.0",
        "# Generated by generate_rebar_station.py; static station plus one",
        "# dynamic rebar (rigid body) resting on two support blocks.",
        "(",
        '    defaultPrim = "World"',
        "    metersPerUnit = 1",
        '    upAxis = "Z"',
        ")",
        "",
        'def Xform "World"',
        "{",
        '    def Xform "RebarStation"',
        "    {",
        f"        double3 xformOp:translate = ({station_x:g}, {station_y:g}, 0)",
        '        uniform token[] xformOpOrder = ["xformOp:translate"]',
        "",
        '        def Material "RebarMaterial" (',
        '            prepend apiSchemas = ["PhysicsMaterialAPI", "PhysxMaterialAPI"]',
        "        )",
        "        {",
        "            float physics:dynamicFriction = 0.8",
        "            float physics:restitution = 0",
        "            float physics:staticFriction = 0.8",
        '            token physxMaterial:frictionCombineMode = "max"',
        "        }",
        "",
        "        # Low-friction supports let the clamped bar slide off smoothly",
        "        # when the gripper lifts it, instead of jamming the arm.",
        '        def Material "SupportMaterial" (',
        '            prepend apiSchemas = ["PhysicsMaterialAPI", "PhysxMaterialAPI"]',
        "        )",
        "        {",
        "            float physics:dynamicFriction = 0.05",
        "            float physics:restitution = 0",
        "            float physics:staticFriction = 0.05",
        '            token physxMaterial:frictionCombineMode = "min"',
        "        }",
        "",
    ]

    # Table top and legs (static colliders, all in station-local coordinates).
    table_size = (0.9, 0.5, 0.04)
    lines.append(
        _cube(
            "TableTop",
            (0, 0, table_height - table_size[2] / 2),
            table_size,
            steel_blue,
            indent=8,
        )
    )
    for leg_index, (lx, ly) in enumerate(
        ((-0.36, -0.18), (0.36, -0.18), (-0.36, 0.18), (0.36, 0.18)), 1
    ):
        leg_height = table_height - table_size[2]
        lines.append(
            _cube(
                f"TableLeg_{leg_index}",
                (lx, ly, leg_height / 2),
                (0.06, 0.06, leg_height),
                steel_blue,
                indent=8,
            )
        )

    # Two low-friction support blocks keep the bar from rolling off the table.
    for block_index, bx in enumerate((-block_offset_x, block_offset_x), 1):
        lines.append(
            _cube(
                f"SupportBlock_{block_index}",
                (bx, 0, table_height + block_size[2] / 2),
                block_size,
                block_yellow,
                indent=8,
                material="SupportMaterial",
            )
        )

    # The rebar itself: the only dynamic rigid body in the station. Axis X
    # keeps it perpendicular to the gripper fingers, which close along Y.
    lines.extend(
        [
            "",
            '        def Cylinder "Rebar" (',
            "            prepend apiSchemas = [",
            '                "PhysicsRigidBodyAPI",',
            '                "PhysicsMassAPI",',
            '                "PhysicsCollisionAPI",',
            '                "MaterialBindingAPI",',
            "            ]",
            "        )",
            "        {",
            '            uniform token axis = "X"',
            f"            double radius = {radius:g}",
            f"            double height = {length:g}",
            f"            color3f[] primvars:displayColor = [({_vec(rust)})]",
            f"            rel material:binding:physics = </World/RebarStation/RebarMaterial>",
            f"            float physics:mass = {mass:.4g}",
            f"            double3 xformOp:translate = (0, 0, {rebar_z:g})",
            '            uniform token[] xformOpOrder = ["xformOp:translate"]',
            "        }",
        ]
    )

    lines.extend(["", "    }", "}", ""])
    return "\n".join(lines), rebar_z


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "urdf" / "rebar_station.usda",
    )
    parser.add_argument(
        "--station-x",
        type=float,
        default=-1.15,
        help="Station centre X in the robot frame (arm workspace opens toward -X)",
    )
    parser.add_argument("--station-y", type=float, default=0.0)
    parser.add_argument(
        "--radius", type=float, default=0.012, help="Rebar radius in metres"
    )
    parser.add_argument(
        "--length", type=float, default=0.6, help="Rebar length in metres"
    )
    parser.add_argument(
        "--table-height", type=float, default=0.45, help="Table top height in metres"
    )
    args = parser.parse_args()

    content, rebar_z = generate(
        args.station_x,
        args.station_y,
        args.radius,
        args.length,
        args.table_height,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    rebar_world_z = args.table_height + 0.06 + args.radius
    print(f"Generated rebar station: {args.output}")
    print(
        f"Rebar centre (world): x={args.station_x:g}, y={args.station_y:g}, "
        f"z={rebar_world_z:g}"
    )


if __name__ == "__main__":
    main()
