#!/usr/bin/env python3
"""Generate a rebar pick-and-place station USD layer for Isaac Sim.

The station sits inside the arm's reach in front of the robot (the arm mount
is rotated 180 degrees about Z, so the arm workspace opens toward -X in the
robot frame). It provides a low table, two support blocks that keep the bar
from rolling, and one dynamic rebar cylinder modelled after the nominal
specimen (24 mm diameter, 0.6 m length). Concave saddles prevent rolling.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from rebar_experiment_geometry import SLOT_X, RACK_REBAR_Z, rack_boxes, saddle_boxes
from generate_rebar_visual import generate as generate_visual, visual_reference

REBAR_DENSITY_KG_M3 = 7850.0


def _vec(values):
    return ", ".join(f"{value:g}" for value in values)


def _cube(name, position, size, color, indent=8, material=None, rpy=(0, 0, 0),
          collision_enabled=True):
    pad = " " * indent
    schemas = ["PhysicsCollisionAPI"]
    body = []
    if material is not None:
        schemas.append("MaterialBindingAPI")
        body.append(
            f"{pad}    rel material:binding:physics = </World/RebarStation/{material}>"
        )
    schema_text = (
        " (\n{}    prepend apiSchemas = [{}]\n{})".format(
            pad, ", ".join(f'"{s}"' for s in schemas), pad
        )
        if schemas
        else ""
    )
    lines = [
        f'{pad}def Cube "{name}"{schema_text}',
        f"{pad}{{",
        f"{pad}    double size = 1",
        f"{pad}    color3f[] primvars:displayColor = [({_vec(color)})]",
        f"{pad}    bool physics:collisionEnabled = {int(collision_enabled)}",
    ]
    lines.extend(body)
    lines.extend(
        [
            f"{pad}    double3 xformOp:translate = ({_vec(position)})",
            f"{pad}    float3 xformOp:rotateXYZ = ({_vec(tuple(math.degrees(v) for v in rpy))})",
            f"{pad}    double3 xformOp:scale = ({_vec(size)})",
            (
                f"{pad}    uniform token[] xformOpOrder = "
                '["xformOp:translate", "xformOp:rotateXYZ", "xformOp:scale"]'
            ),
            f"{pad}}}",
        ]
    )
    return "\n".join(lines)


def rigid_contact_settings(indent):
    """Increase contact solver iterations without changing drag or offsets."""
    pad = " " * indent
    return "\n".join(pad + line for line in (
        "int physxRigidBody:solverPositionIterationCount = 32",
        "int physxRigidBody:solverVelocityIterationCount = 8",
    ))


def generate(
    station_x,
    station_y,
    radius,
    length,
    table_height,
):
    # Steel bar mass from the cylinder volume; keeps grip-force math honest.
    mass = REBAR_DENSITY_KG_M3 * 3.141592653589793 * radius**2 * length

    # Keep the supports well inside the ends for every configured bar length.
    block_size = (0.1, 0.06, 0.054)
    block_offset_x = length * 0.3
    rebar_z = table_height + 0.06 + radius

    rust = (0.45, 0.3, 0.2)
    steel_blue = (0.18, 0.24, 0.32)
    block_yellow = (0.85, 0.65, 0.1)

    lines = [
        "#usda 1.0",
        "# Generated by generate_rebar_station.py; static station plus one",
        "# dynamic rebar (rigid body) resting on two support blocks.",
        "(",
        '    defaultPrim = "World"',
        "    metersPerUnit = 1",
        '    upAxis = "Z"',
        ")",
        "",
        'def Xform "World"',
        "{",
        '    def Xform "RebarStation"',
        "    {",
        f"        double3 xformOp:translate = ({station_x:g}, {station_y:g}, 0)",
        '        uniform token[] xformOpOrder = ["xformOp:translate"]',
        "",
        '        def Material "RebarMaterial" (',
        '            prepend apiSchemas = ["PhysicsMaterialAPI", "PhysxMaterialAPI"]',
        "        )",
        "        {",
        "            float physics:dynamicFriction = 0.8",
        "            float physics:restitution = 0",
        "            float physics:staticFriction = 0.8",
        '            token physxMaterial:frictionCombineMode = "max"',
        "        }",
        "",
        "        # Low-friction supports let the clamped bar slide off smoothly",
        "        # when the gripper lifts it, instead of jamming the arm.",
        '        def Material "SupportMaterial" (',
        '            prepend apiSchemas = ["PhysicsMaterialAPI", "PhysxMaterialAPI"]',
        "        )",
        "        {",
        "            float physics:dynamicFriction = 0.05",
        "            float physics:restitution = 0",
        "            float physics:staticFriction = 0.05",
        '            token physxMaterial:frictionCombineMode = "min"',
        "        }",
        "",
    ]

    # Table top and legs (static colliders, all in station-local coordinates).
    table_size = (0.9, 0.5, 0.04)
    lines.append(
        _cube(
            "TableTop",
            (0, 0, table_height - table_size[2] / 2),
            table_size,
            steel_blue,
            indent=8,
        )
    )
    for leg_index, (lx, ly) in enumerate(
        ((-0.36, -0.18), (0.36, -0.18), (-0.36, 0.18), (0.36, 0.18)), 1
    ):
        leg_height = table_height - table_size[2]
        lines.append(
            _cube(
                f"TableLeg_{leg_index}",
                (lx, ly, leg_height / 2),
                (0.06, 0.06, leg_height),
                steel_blue,
                indent=8,
            )
        )

    # Short pedestals with concave arc segments; the gripper reaches the free
    # central span, and the bar lifts vertically out of the open saddles.
    for block_index, bx in enumerate((-block_offset_x, block_offset_x), 1):
        lines.append(
            _cube(
                f"SupportBlock_{block_index}",
                (bx, 0, table_height + block_size[2] / 2),
                block_size,
                block_yellow,
                indent=8,
                material="SupportMaterial",
            )
        )
        for segment, (position, size, rpy) in enumerate(
            saddle_boxes("X", (bx, 0, table_height + 0.076),
                         width=0.1, radius=0.016), 1
        ):
            lines.append(_cube(
                f"SourceSaddle{block_index}_{segment}", position, size,
                block_yellow, material="SupportMaterial", rpy=rpy,
            ))

    # The rebar itself: the only dynamic rigid body in the station. Axis X
    # keeps it perpendicular to the gripper fingers, which close along Y.
    lines.extend(
        [
            "",
            '        def Cylinder "Rebar" (',
            "            prepend apiSchemas = [",
            '                "PhysicsRigidBodyAPI",',
            '                "PhysicsMassAPI",',
            '                "PhysicsCollisionAPI",',
            '                "PhysxRigidBodyAPI",',
            '                "MaterialBindingAPI",',
            "            ]",
            "        )",
            "        {",
            '            uniform token axis = "X"',
            f"            double radius = {radius:g}",
            f"            double height = {length:g}",
            f"            color3f[] primvars:displayColor = [({_vec(rust)})]",
            f"            rel material:binding:physics = </World/RebarStation/RebarMaterial>",
            f"            float physics:mass = {mass:.4g}",
            rigid_contact_settings(indent=12),
            f"            double3 xformOp:translate = (0, 0, {rebar_z:g})",
            '            uniform token[] xformOpOrder = ["xformOp:translate"]',
            visual_reference('X', radius, length),
            "        }",
        ]
    )

    lines.extend(["", "    }", "}", ""])
    return "\n".join(lines), rebar_z


def generate_rack():
    lines = [
        '#usda 1.0', '(\n    metersPerUnit = 1\n    upAxis = "Z"\n)',
        'over "World" {', '    over "seer_aubo_composite" {',
        '        over "base_link" {', '            def Xform "RebarRack" {',
    ]
    for name, position, size, rpy in rack_boxes():
        color = (.16, .22, .28) if name.startswith("MountingBeam") else (.2, .5, .65)
        lines.append(_cube(name, position, size, color,
                           indent=16, rpy=rpy,
                           collision_enabled=not (
                               'Saddle' in name and 4 <= int(name.rsplit('_', 1)[1]) <= 11)))
    lines.extend(['            }', '        }', '    }', '}', ''])
    return '\n'.join(lines)


def generate_prefilled():
    """Three independent dynamic bars for checking neighbouring occupied slots."""
    lines = ['#usda 1.0', '(', '    metersPerUnit = 1', '    upAxis = "Z"',
             '    subLayers = [@./warehouse_finger_rebar_loading_demo.usda@]', ')',
             'over "World" {']
    mass = REBAR_DENSITY_KG_M3 * math.pi * .012**2 * .6
    for slot in (2, 3, 4):
        lines.extend([
            f'    def Cylinder "LoadedRebar{slot}" (',
            '        prepend apiSchemas = ["PhysicsRigidBodyAPI", "PhysicsMassAPI",',
            '                              "PhysicsCollisionAPI", "MaterialBindingAPI",',
            '                              "PhysxRigidBodyAPI"]',
            '    ) {', '        uniform token axis = "Y"',
            '        double radius = 0.012', '        double height = 0.6',
            f'        float physics:mass = {mass:.4g}',
            rigid_contact_settings(indent=8),
            '        color3f[] primvars:displayColor = [(0.45, 0.3, 0.2)]',
            '        rel material:binding:physics = </World/RebarStation/RebarMaterial>',
            f'        double3 xformOp:translate = ({SLOT_X[slot-1]}, 0, {RACK_REBAR_Z})',
            '        uniform token[] xformOpOrder = ["xformOp:translate"]',
            visual_reference('Y', indent=8, parent_path=f'/World/LoadedRebar{slot}'), '    }',
        ])
    return '\n'.join(lines + ['}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "urdf" / "rebar_station.usda",
    )
    parser.add_argument(
        "--station-x",
        type=float,
        default=-1.15,
        help="Station centre X in the robot frame (arm workspace opens toward -X)",
    )
    parser.add_argument("--station-y", type=float, default=0.0)
    parser.add_argument(
        "--radius", type=float, default=0.012, help="Rebar radius in metres"
    )
    parser.add_argument(
        "--length", type=float, default=0.6, help="Rebar length in metres"
    )
    parser.add_argument(
        "--table-height", type=float, default=0.45, help="Table top height in metres"
    )
    args = parser.parse_args()

    content, rebar_z = generate(
        args.station_x,
        args.station_y,
        args.radius,
        args.length,
        args.table_height,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    generate_visual(args.output.parent)
    args.output.write_text(content, encoding="utf-8")
    rack_output = args.output.with_name("rebar_onboard_rack.usda")
    rack_output.write_text(generate_rack(), encoding="utf-8")
    args.output.with_name("warehouse_finger_rebar_loading_prefilled_demo.usda").write_text(
        generate_prefilled(), encoding="utf-8")
    rebar_world_z = args.table_height + 0.06 + args.radius
    print(f"Generated rebar station: {args.output}")
    print(
        f"Rebar centre (world): x={args.station_x:g}, y={args.station_y:g}, "
        f"z={rebar_world_z:g}"
    )


if __name__ == "__main__":
    main()
