cmake_minimum_required(VERSION 3.8)
project(aubo_control_gui)
find_package(ament_cmake REQUIRED)
find_package(ament_cmake_python REQUIRED)
ament_python_install_package(aubo_control_gui)
install(PROGRAMS scripts/aubo_control_gui DESTINATION lib/${PROJECT_NAME})
install(DIRECTORY launch qml config DESTINATION share/${PROJECT_NAME})
install(FILES README.md KEY_POSITION_VALIDATION.md DESTINATION share/${PROJECT_NAME})
ament_package()
